// android-patch/apply.js
// Run after: npx cap sync android
// Usage:     npm run android:patch   (or: npm run android:sync)
//
// Applies the following patches to the Android project:
//   1. styles.xml            — dark status/nav bar + dark splash (no white flash)
//   2. colors.xml            — icon background (white) + splash background (dark)
//   3. mipmap icons          — ic_launcher.png + ic_launcher_round.png (all densities)
//   4. ic_launcher_foreground.png — adaptive icon foreground (Android 8+), generated
//                                   by the CI ImageMagick step or falls back to same PNG
//   5. mipmap-anydpi-v26 XMLs — ic_launcher.xml + ic_launcher_round.xml (adaptive icon)
//   6. strings.xml           — sets app_name to "Dud Dairy"

import { copyFileSync, existsSync, mkdirSync, readdirSync, writeFileSync } from 'fs'
import { resolve, dirname, join } from 'path'
import { fileURLToPath } from 'url'

const __dirname   = dirname(fileURLToPath(import.meta.url))
const root        = resolve(__dirname, '..')
const androidRes  = resolve(root, 'android', 'app', 'src', 'main', 'res')
const patchRes    = resolve(__dirname, 'res')

if (!existsSync(resolve(root, 'android'))) {
  console.error('ERROR: android/ folder not found.')
  console.error('       Run: npx cap add android && npx cap sync android  — then retry.')
  process.exit(1)
}

// ─── helper ──────────────────────────────────────────────────────────────────
function ensureDir(dir) {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
}

function copyFile(src, dest) {
  ensureDir(dirname(dest))
  copyFileSync(src, dest)
}

// ─── 1. styles.xml ───────────────────────────────────────────────────────────
copyFile(
  resolve(__dirname, 'styles.xml'),
  resolve(androidRes, 'values', 'styles.xml')
)
console.log('✓ styles.xml — dark status bar + dark splash')

// ─── 2. colors.xml ───────────────────────────────────────────────────────────
copyFile(
  resolve(patchRes, 'values', 'colors.xml'),
  resolve(androidRes, 'values', 'colors.xml')
)
console.log('✓ colors.xml — icon background + splash colours')

// ─── 3 & 4. mipmap PNG icons ─────────────────────────────────────────────────
const mipmapFolders = [
  'mipmap-mdpi',
  'mipmap-hdpi',
  'mipmap-xhdpi',
  'mipmap-xxhdpi',
  'mipmap-xxxhdpi',
]

for (const folder of mipmapFolders) {
  const srcDir  = resolve(patchRes, folder)
  const destDir = resolve(androidRes, folder)
  if (!existsSync(srcDir)) continue
  ensureDir(destDir)

  for (const file of readdirSync(srcDir)) {
    // Copy ic_launcher.png + ic_launcher_round.png
    copyFile(join(srcDir, file), join(destDir, file))

    // Also copy ic_launcher.png → ic_launcher_foreground.png
    // (proper foreground PNGs are generated by the CI ImageMagick step;
    //  this fallback ensures the build still works locally)
    if (file === 'ic_launcher.png') {
      const fgDest = join(destDir, 'ic_launcher_foreground.png')
      // Only write fallback if a proper CI-generated version doesn't already exist
      // (CI step writes ic_launcher_foreground.png BEFORE apply.js runs)
      if (!existsSync(fgDest)) {
        copyFile(join(srcDir, file), fgDest)
        console.log(`  ↳ fallback foreground: ${folder}/ic_launcher_foreground.png`)
      } else {
        console.log(`  ↳ CI foreground kept: ${folder}/ic_launcher_foreground.png`)
      }
    }
  }
  console.log(`✓ ${folder} icons`)
}

// ─── 5. mipmap-anydpi-v26 adaptive icon XMLs ─────────────────────────────────
const anydpiSrc  = resolve(patchRes, 'mipmap-anydpi-v26')
const anydpiDest = resolve(androidRes, 'mipmap-anydpi-v26')
ensureDir(anydpiDest)

for (const file of readdirSync(anydpiSrc)) {
  copyFile(join(anydpiSrc, file), join(anydpiDest, file))
}
console.log('✓ mipmap-anydpi-v26 — adaptive icon XMLs (Android 8+)')

// ─── 6. strings.xml — set app name ───────────────────────────────────────────
const stringsSrc  = resolve(androidRes, 'values', 'strings.xml')
const appName     = 'Dud Dairy'

if (existsSync(stringsSrc)) {
  const { readFileSync } = await import('fs')
  const original = readFileSync(stringsSrc, 'utf8')
  const patched  = original.replace(
    /<string name="app_name">.*?<\/string>/,
    `<string name="app_name">${appName}</string>`
  )
  if (patched !== original) {
    writeFileSync(stringsSrc, patched, 'utf8')
    console.log(`✓ strings.xml — app_name set to "${appName}"`)
  } else {
    console.log(`  strings.xml — app_name already "${appName}" or tag not found`)
  }
} else {
  console.log('  strings.xml — not found, skipping')
}

console.log('\n✅ All Android patches applied successfully.')
